name: CD - Build and Push Docker Image

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: travelplanner-api
  DOCKERFILE_PATH: TravelPlanner/TravelPlanner.Api/Dockerfile
  CONTEXT_PATH: TravelPlanner

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lowercase image ref (GHCR requires lowercase)
        id: img
        run: |
          OWNER_LC="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
          echo "IMAGE_REF=ghcr.io/${OWNER_LC}/${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: ${{ steps.img.outputs.IMAGE_REF }}
            tags: |
              type=sha
              type=ref,event=branch
              type=ref,event=tag
              type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT_PATH }}
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

